apiVersion: v1
kind: Service
metadata:
  name: svc-nodejs-app
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 31000 
    type: NodePort    